In [1]:
import pandas as pd
data1 = {
  "name": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

data2 = {
  "name": ["Sally", "Peter", "Micky"],
  "age": [77, 44, 22]
}
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [2]:
newdf=df1.merge(df2,how='right')

In [3]:
newdf

    name  age
0  Sally   77
1  Peter   44
2  Micky   22

In [4]:
df1 = pd.DataFrame({'name': ['Alice']})
df2 = pd.DataFrame({'name': ['Bob']})

result = pd.concat([df1, df2])
result

    name
0  Alice
0    Bob

In [5]:
#1. Simple Concat (Rows)
#Task: Combine them into a single DataFrame with all 4 names.
df1=pd.DataFrame({'name':['Alice','Bob']})
df2=pd.DataFrame({'name':['Charlie','David']})

In [ ]:
result=pd.concat([df1,df2],ignore_index=True)
result
#alternative: result = result.reset_index(drop=True)

      name
0    Alice
1      Bob
0  Charlie
1    David

In [7]:
#2 Simple Concat (Columns)
df1 = pd.DataFrame({'name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'age': [25, 30]})
result=pd.concat([df1,df2],axis=1)
result

    name  age
0  Alice   25
1    Bob   30

In [ ]:
#3 Basic Merge
df1 = pd.DataFrame({'id': [1, 2], 'name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'id': [1, 2], 'score': [90, 85]})
result=df1.merge(df2,how='inner',on='id')
result
#alternative: result = df1.merge(df2, on='id') since inner is the default in pandas

   id   name  score
0   1  Alice     90
1   2    Bob     85

In [11]:
#4 Left Join Practice
df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [1, 2], 'score': [90, 85]})
result=df1.merge(df2,how='left',on='id')
result

   id     name  score
0   1    Alice   90.0
1   2      Bob   85.0
2   3  Charlie    NaN

In [12]:
#5 Outer Join
result=df1.merge(df2,how='outer',on='id')
result

   id     name  score
0   1    Alice   90.0
1   2      Bob   85.0
2   3  Charlie    NaN

In [ ]:
#6 Concat with Different Columns
df1 = pd.DataFrame({'name': ['Alice'], 'age': [25]})
df2 = pd.DataFrame({'name': ['Bob'], 'score': [90]})
result=pd.concat([df1,df2], ignore_index=True)
result

    name   age  score
0  Alice  25.0    NaN
0    Bob   NaN   90.0

In [ ]:
#7 Multi-Key Merge
df1 = pd.DataFrame({
    'id': [1, 1, 2],
    'subject': ['Math', 'English', 'Math'],
    'score': [90, 85, 88]
})

df2 = pd.DataFrame({
    'id': [1, 2],
    'name': ['Alice', 'Bob']
})
result=df1.merge(df2,on='id')
result

   id  subject  score   name
0   1     Math     90  Alice
1   1  English     85  Alice
2   2     Math     88    Bob

In [ ]:
#8 Concat with Index Reset
df1 = pd.DataFrame({'name': ['Alice', 'Bob']}, index=[0, 1])
df2 = pd.DataFrame({'name': ['Charlie']}, index=[0])
result=pd.concat([df1,df2],ignore_index=True) #is this resetting index?
result

      name
0    Alice
1      Bob
2  Charlie

In [32]:
#9 Real-World Scenario (Sales Data)
jan = pd.DataFrame({'product': ['A', 'B'], 'sales': [100, 150]})
feb = pd.DataFrame({'product': ['A', 'B'], 'sales': [120, 130]})
combined_months=pd.concat([jan,feb],ignore_index=True)
combined_months['month'] = ['Jan'] * len(jan) + ['Feb'] * len(feb)
combined_months

  product  sales month
0       A    100   Jan
1       B    150   Jan
2       A    120   Feb
3       B    130   Feb

In [22]:
#10 Merge + Concat Combined
users = pd.DataFrame({'id': [1, 2], 'name': ['Alice', 'Bob']})
orders1 = pd.DataFrame({'id': [1], 'order': ['Book']})
orders2 = pd.DataFrame({'id': [2], 'order': ['Pen']})
orders_all=pd.concat([orders1,orders2],ignore_index=True)
orders_all

   id order
0   1  Book
1   2   Pen

In [23]:
merged=orders_all.merge(users,how='left',on='id')
merged

   id order   name
0   1  Book  Alice
1   2   Pen    Bob

In [33]:
#11 Detect Differences After Concat
#given two datasets old vs new
old = pd.DataFrame({'id': [1, 2], 'value': [10, 20]})
new = pd.DataFrame({'id': [2, 3], 'value': [25, 30]})
combined = old.merge(new, on='id', how='outer', indicator=True)
combined

   id  value_x  value_y      _merge
0   1     10.0      NaN   left_only
1   2     20.0     25.0        both
2   3      NaN     30.0  right_only

In [34]:
#now to extract the desired rows:
#New rows
combined[combined['_merge'] == 'right_only']

   id  value_x  value_y      _merge
2   3      NaN     30.0  right_only

In [35]:
#Updated rows
both = combined[combined['_merge'] == 'both']
both[both['value_x'] != both['value_y']]

   id  value_x  value_y _merge
1   2     20.0     25.0   both