In [1]:
import pandas as pd
import numpy as np

In [2]:

import kagglehub
path = kagglehub.dataset_download("prasad22/healthcare-dataset")
print("Path to dataset files:", path)

c:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/prasad22/healthcare-dataset?dataset_version_number=2...

100%|██████████| 2.91M/2.91M [00:01<00:00, 2.99MB/s]

Extracting files...
Path to dataset files: C:\Users\X\.cache\kagglehub\datasets\prasad22\healthcare-dataset\versions\2

In [3]:
from pathlib import Path
root = Path(r"C:\Users\X\.cache\kagglehub\datasets\prasad22\healthcare-dataset\versions\2")
for p in sorted(root.iterdir()):
    print(p.name)

healthcare_dataset.csv

In [5]:
df = pd.read_csv(root / "healthcare_dataset.csv")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [6]:
print(df.shape)

(55500, 15)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [12]:
#normalize the name values
df['Name'] = df['Name'].str.title()
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
#check for nulls
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [14]:
int(df.duplicated().sum())

534

In [16]:
df = df.drop_duplicates()
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [22]:
#above 50 years
df_above_50=df[df["Age"] > 50].sort_values("Age", ascending=True)
df_above_50

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
42860,Steven Boyer,51,Male,O-,Cancer,2019-07-11,George Arroyo,Sheppard PLC,Cigna,3988.850158,221,Elective,2019-07-31,Ibuprofen,Normal
7813,Michael Kemp,51,Female,AB+,Diabetes,2023-06-26,Bobby Benjamin,Jones Sons and,Medicare,48365.584175,370,Elective,2023-07-26,Paracetamol,Abnormal
8028,James Hall,51,Female,AB+,Cancer,2023-08-11,Anthony Clark,"Woods Lewis Dennis, and",UnitedHealthcare,7163.060068,357,Emergency,2023-08-13,Penicillin,Normal
42923,Dominique Williams,51,Female,A-,Cancer,2023-11-08,Lee Johnson,LLC Jones,UnitedHealthcare,45283.309273,434,Elective,2023-11-12,Ibuprofen,Inconclusive
8200,Wayne Hurst,51,Male,B+,Arthritis,2022-03-08,Benjamin Jones,Brown-Sims,Aetna,8403.901808,265,Emergency,2022-04-03,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52372,Deborah Mcbride,89,Female,O+,Obesity,2021-05-28,Robert Garcia,"and Miller, Olson Olson",Cigna,5692.907188,166,Elective,2021-06-13,Paracetamol,Abnormal
52828,Donald Avila,89,Female,AB-,Asthma,2022-09-17,Christopher Allen,"Holmes and Howard Castro,",Aetna,14042.748908,199,Emergency,2022-09-27,Aspirin,Abnormal
55385,Heather Dawson,89,Male,O-,Arthritis,2022-07-18,Ann Hall,Moore-Gray,Aetna,17172.115995,455,Elective,2022-08-13,Ibuprofen,Normal
52043,David Newton,89,Female,O+,Arthritis,2021-02-08,Jerry Hopkins,"Cooper Brown Parks, and",Aetna,34500.016817,242,Elective,2021-02-20,Penicillin,Inconclusive
53825,Michael Potts,89,Male,A+,Hypertension,2023-01-19,Mary Vaughn,"and Perez, Bennett Townsend",Cigna,9542.739709,289,Emergency,2023-01-28,Paracetamol,Abnormal

In [32]:
#to see the different types of diseases
df_above_50['Medical Condition'].unique()

array(['Cancer', 'Diabetes', 'Arthritis', 'Asthma', 'Obesity',
       'Hypertension'], dtype=object)

In [35]:
#to see how many people are sick from the diseases
df_above_50.groupby('Medical Condition')['Name'].count().sort_values(ascending=True)

Medical Condition
Obesity         4690
Asthma          4696
Cancer          4737
Arthritis       4745
Diabetes        4763
Hypertension    4763
Name: Name, dtype: int64

In [30]:
multi_disease = df_above_50.groupby('Name')['Medical Condition'].nunique() #nunique() -> count how many unique (distinct) values exist
multi_disease
multi_disease[multi_disease > 1]

Name
Aaron Baker          2
Aaron Davis          2
Aaron Jackson        2
Aaron Lopez          2
Aaron Miller         2
                    ..
Zachary Hernandez    2
Zachary Johnson      2
Zachary Miller       2
Zachary Moore        2
Zachary Reed         2
Name: Medical Condition, Length: 1989, dtype: int64

In [37]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
df['Age'].describe() #discribe -> it summarizes the distribution of age
#25% of patients are 35 or younger and so on

count    54966.000000
mean        51.535185
std         19.605661
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

In [39]:
df['Gender'].value_counts()

Gender
Male      27496
Female    27470
Name: count, dtype: int64

In [41]:
#average billing per disease
df.groupby('Medical Condition')['Billing Amount'].mean().sort_values(ascending=False)

Medical Condition
Obesity         25804.361902
Diabetes        25660.478635
Asthma          25633.461696
Arthritis       25511.783246
Hypertension    25503.058720
Cancer          25152.322947
Name: Billing Amount, dtype: float64

In [ ]:
#below or eq 50 years
df[df["Age"] <= 50].sort_values("Age", ascending=True)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55382,Kristin Ortiz,13,Male,A-,Asthma,2020-04-01,Donna Fernandez,"Yu and Mckenzie Lucas,",UnitedHealthcare,50526.712855,493,Urgent,2020-04-02,Paracetamol,Abnormal
54302,Dawn Chavez,13,Male,AB+,Cancer,2023-03-13,David Mcclure,"Taylor, Boyle Dalton and",UnitedHealthcare,43935.226905,478,Emergency,2023-03-25,Ibuprofen,Abnormal
51095,Cathy Barnes,13,Male,O-,Obesity,2023-03-30,Kevin Ellison,Wood-Johnson,Medicare,29170.617795,348,Emergency,2023-04-29,Lipitor,Abnormal
53590,Jessica Chung,13,Male,AB+,Obesity,2020-07-06,Leah Hancock,Davis-Lawrence,Blue Cross,32019.913320,129,Urgent,2020-07-11,Aspirin,Abnormal
51873,Dorothy Hoffman,13,Female,O-,Cancer,2020-07-18,Suzanne Jones,"Davis Davis, and Davis",Cigna,22316.169323,379,Elective,2020-08-10,Ibuprofen,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7999,David Walters,50,Female,AB-,Arthritis,2022-04-08,Victoria Christensen,Scott-Luna,UnitedHealthcare,13064.433444,319,Emergency,2022-04-15,Aspirin,Normal
32724,Jason James,50,Male,AB+,Arthritis,2022-11-28,Daniel Dixon,"Nixon, Baldwin Perry and",UnitedHealthcare,13488.567013,109,Urgent,2022-11-30,Paracetamol,Normal
55369,Thomas Gibson,50,Female,A+,Diabetes,2024-03-11,Matthew Maynard,"Harris Wilson, Jacobson and",Aetna,31391.444546,420,Elective,2024-03-15,Lipitor,Normal
37908,Erik Stewart,50,Male,O-,Arthritis,2024-03-29,Ronald Mcdonald,Ltd Spencer,Medicare,9924.898926,190,Emergency,2024-04-07,Lipitor,Abnormal
37994,Benjamin Russell,50,Female,AB+,Obesity,2022-04-15,Ryan Barton,"Wright Gonzalez, and Griffin",UnitedHealthcare,6333.117899,313,Urgent,2022-05-08,Lipitor,Normal